export let data = [
    {
      titulo: "Cambio de pasta térmica",
      img: "https://www.opirata.com/blog/wp-content/uploads/2019/04/pasta-termica.jpg",
      descripcion: "Cómo cambiar la pasta térmica del procesador",
      herramientas: [
        "Destornillador de estrella",
        "Paño de microfibra",
        "Pasta térmica",
      ],
      pasos: [
        "Apaga y desconecta el equipo completamente.",
        "Retira la tapa del equipo para acceder al procesador.",
        "Con el destornillador de estrella, afloja los tornillos que sujetan el disipador de calor al procesador.",
        "Con cuidado, levanta el disipador de calor para revelar el procesador.",
        "Usando el paño de microfibra, limpia suavemente la pasta térmica vieja del procesador y del disipador de calor.",
        "Aplica una pequeña cantidad de pasta térmica nueva en el centro del procesador. No exageres la cantidad, ya que puede tener efectos contraproducentes.",
        "Con el disipador de calor limpio, presiónalo suavemente sobre el procesador con la pasta térmica aplicada.",
        "Vuelve a apretar los tornillos del disipador de calor para asegurarlo en su lugar. Asegúrate de no apretar demasiado.",
        "Vuelve a colocar la tapa del equipo.",
        "Conecta y enciende el equipo.",
        "Verifica la temperatura del procesador para asegurarte de que la pasta térmica esté funcionando correctamente.",
      ],
    },
    {
      titulo: "Reemplazo de batería de portátil",
      img: "https://sistemas.com/wp-content/uploads/2014/08/bateria_newertech_3.jpg",
      descripcion: "Cómo reemplazar la batería de un portátil",
      herramientas: [
        "Destornillador",
        "Batería de reemplazo compatible",
        "Pinzas",
      ],
      pasos: [
        "Apaga el portátil y desconéctalo de la fuente de alimentación.",
        "Voltea el portátil y busca la tapa de la batería.",
        "Usando el destornillador, retira los tornillos que sujetan la tapa de la batería en su lugar.",
        "Con cuidado, levanta la tapa de la batería y desconecta la batería vieja.",
        "Coloca la batería de reemplazo en su lugar y conéctala correctamente.",
        "Vuelve a colocar y aprieta los tornillos de la tapa de la batería.",
        "Gira el portátil y conéctalo nuevamente a la fuente de alimentación.",
        "Carga la batería completamente antes de usarla sin estar conectada.",
        "Verifica que la nueva batería esté funcionando correctamente.",
      ],
    },
    {
      titulo: "Limpieza de ventiladores de PC",
      img: "https://www.reviewhardware.com/wp-content/uploads/2018/11/Limpiar-ventiladores-PC.jpg",
      descripcion: "Cómo limpiar los ventiladores de un PC",
      herramientas: [
        "Lata de aire comprimido",
        "Destornillador",
        "Paño de microfibra",
      ],
      pasos: [
        "Apaga y desconecta el PC.",
        "Abre la carcasa del PC con el destornillador.",
        "Ubica los ventiladores dentro del PC.",
        "Usa la lata de aire comprimido para soplar aire en los ventiladores y eliminar el polvo acumulado.",
        "Con el paño de microfibra, limpia las aspas de los ventiladores con cuidado.",
        "Verifica que no queden restos de polvo o pelusas.",
        "Vuelve a cerrar la carcasa del PC.",
        "Conecta y enciende el PC.",
        "Monitorea la temperatura del PC para asegurarte de que los ventiladores funcionen correctamente.",
      ],
    },
    {
      titulo: "Formateo e instalación de sistema operativo",
      img: "https://cdn.computerhoy.com/sites/navi.axelspringer.es/public/media/image/2017/05/239118-formatear-disco-duro-instalar-windows-problema-formato-ntfs.jpg?tf=3840x",
      descripcion: "Cómo formatear e instalar un sistema operativo",
      herramientas: [
        "Disco de instalación del sistema operativo",
        "Destornillador",
        "Respaldo de datos (opcional)",
      ],
      pasos: [
        "Haz una copia de seguridad de tus datos importantes si es necesario.",
        "Inserta el disco de instalación del sistema operativo en la unidad correspondiente.",
        "Reinicia el equipo y accede a la configuración de arranque (puedes usar una tecla como F12 o Del durante el inicio).",
        "Selecciona la unidad de la que quieres arrancar (el disco de instalación del sistema operativo).",
        "Sigue las instrucciones en pantalla para iniciar el proceso de instalación.",
        "Selecciona la opción para formatear el disco duro y sigue las instrucciones para completar el formateo.",
        "Sigue las instrucciones para instalar el sistema operativo en el disco recién formateado.",
        "Una vez finalizada la instalación, reinicia el equipo.",
        "Realiza la configuración inicial del sistema operativo, como idioma, zona horaria, etc.",
        "Si hiciste una copia de seguridad, restaura tus datos y archivos importantes.",
        "Verifica que el sistema operativo se haya instalado correctamente y funciona sin problemas.",
      ],
    },
    {
      titulo: "Instalación de memoria RAM",
      img: "https://www.digitaltoo.com/wp-content/uploads/sites/3/2021/04/Cambiar-memoria-RAM-1-1080x770.jpg",
      descripcion: "Cómo instalar memoria RAM en un PC",
      herramientas: [
        "Destornillador",
        "Nueva memoria RAM compatible",
      ],
      pasos: [
        "Apaga el PC y desconéctalo de la fuente de alimentación.",
        "Ubica las ranuras de memoria RAM en la placa base.",
        "Usando el destornillador, abre los clips de las ranuras de memoria RAM.",
        "Retira las memorias RAM viejas, si las hay, tirando suavemente hacia afuera.",
        "Toma la nueva memoria RAM y alinea cuidadosamente las muescas con las ranuras de la placa base.",
        "Inserta la memoria RAM en las ranuras hasta que los clips se cierren automáticamente.",
        "Vuelve a conectar el PC a la fuente de alimentación.",
        "Enciende el PC y verifica que la memoria RAM se haya instalado correctamente.",
        "Si el PC no se inicia, asegúrate de que la memoria RAM esté bien instalada y sea compatible con la placa base.",
      ],
    },
    {
      titulo: "Reemplazo de pantalla de smartphone",
      img: "https://recambiostablet.com/blog/wp-content/uploads/2019/08/precio-cambiar-pantalla-del-movil.jpg",
      descripcion: "Cómo reemplazar la pantalla de un smartphone",
      herramientas: [
        "Destornillador",
        "Pantalla de reemplazo compatible",
        "Ventosa",
        "Pinzas",
        "Herramientas de apertura de plástico",
      ],
      pasos: [
        "Apaga el smartphone y retira la batería (si es posible).",
        "Usa las herramientas de apertura de plástico para abrir suavemente la carcasa del smartphone.",
        "Desconecta los cables flexibles que conectan la pantalla a la placa base.",
        "Usa el destornillador para quitar los tornillos que sujetan la pantalla al chasis del smartphone.",
        "Con cuidado, levanta la pantalla rota y retírala por completo.",
        "Coloca la pantalla de reemplazo en su lugar y vuelve a conectar los cables flexibles.",
        "Vuelve a colocar los tornillos en su posición original.",
        "Usa la ventosa para eliminar cualquier polvo o partículas entre la pantalla y el smartphone.",
        "Presiona suavemente la nueva pantalla para asegurar una buena adhesión.",
        "Vuelve a colocar la carcasa del smartphone y apriétala hasta que encaje correctamente.",
        "Enciende el smartphone y verifica que la nueva pantalla funcione correctamente.",
      ],
    },
    {
      titulo: "Configuración de red doméstica",
      img: "https://www.redeszone.net/app/uploads-redeszone.net/2022/03/configurar-tu-red-01.jpg",
      descripcion: "Cómo configurar una red doméstica",
      herramientas: [
        "Router inalámbrico",
        "Computadora o dispositivo para configuración",
        "Cables Ethernet (opcional)",
      ],
      pasos: [
        "Conecta el router a la fuente de alimentación y al módem de internet.",
        "Conecta el router a la computadora o dispositivo para la configuración mediante un cable Ethernet o a través de Wi-Fi.",
        "Abre un navegador web e ingresa la dirección IP del router (generalmente 192.168.1.1 o 192.168.0.1).",
        "Ingresa el nombre de usuario y la contraseña para acceder a la configuración del router (consulta el manual del router para las credenciales predeterminadas).",
        "Sigue el asistente de configuración del router para establecer el nombre de red (SSID) y la contraseña.",
        "Elige el tipo de seguridad que deseas utilizar (WPA2 es el más seguro) y configura la contraseña de la red.",
        "Personaliza la configuración del router según tus necesidades (opciones de seguridad adicionales, filtrado de direcciones MAC, etc.).",
        "Guarda los cambios y reinicia el router si es necesario.",
        "Desconecta el cable Ethernet (si lo utilizaste) y conecta tus dispositivos a la red Wi-Fi utilizando la nueva contraseña.",
        "Verifica que los dispositivos estén conectados correctamente a la red y que puedan acceder a internet.",
      ],
    },
    {
      titulo: "Instalación de software antivirus",
      img: "https://seguidores.online/wp-content/uploads/2020/11/Como-instalar-un-antivirus-9-1024x614.jpg",
      descripcion: "Cómo instalar software antivirus en una computadora",
      herramientas: [
        "Disco de instalación del software antivirus",
        "Computadora con conexión a internet",
      ],
      pasos: [
        "Conecta la computadora a internet si no lo está.",
        "Inserta el disco de instalación del software antivirus en la unidad correspondiente.",
        "Sigue las instrucciones en pantalla para iniciar el proceso de instalación.",
        "Lee y acepta los términos y condiciones del software antivirus.",
        "Elige las opciones de instalación (recomendadas o personalizadas).",
        "Espera a que se complete la instalación del software antivirus.",
        "Realiza una actualización del software antivirus para asegurarte de tener la última versión y las últimas definiciones de virus.",
        "Realiza un análisis completo del sistema para buscar y eliminar posibles amenazas.",
        "Configura el software antivirus según tus preferencias (programar análisis, acciones ante detección de amenazas, etc.).",
        "Verifica que el software antivirus esté funcionando correctamente y protegiendo tu computadora.",
      ],
    },
    {
      titulo: "Configuración de impresora",
      img: "https://descubrecomohacerlo.com/wp-content/uploads/mch/configurar-impresora_2735.jpg",
      descripcion: "Cómo configurar una impresora en una computadora",
      herramientas: [
        "Impresora con cable USB o inalámbrica",
        "Computadora con conexión a internet",
        "Cable USB (si es una impresora con conexión USB)",
      ],
      pasos: [
        "Conecta la impresora a la fuente de alimentación y asegúrate de que esté encendida.",
        "Conecta la impresora a la computadora mediante un cable USB (si es necesario) o configúrala para conectarse a través de Wi-Fi.",
        "Espera a que la computadora reconozca la impresora y descargue los controladores necesarios (si es una impresora nueva).",
        "Selecciona la impresora que deseas configurar y sigue las instrucciones en pantalla para completar la configuración.",
        "Si es una impresora inalámbrica, asegúrate de que esté conectada a la misma red Wi-Fi que la computadora.",
        "Realiza una prueba de impresión para verificar que la impresora esté configurada correctamente.",
        "Si tienes problemas con la configuración, consulta el manual de la impresora o visita el sitio web del fabricante para obtener ayuda adicional.",
      ],
    },
    {
      titulo: "Recuperación de datos de disco duro dañado",
      img: "https://www.ondata.es/img/recuperacion/discos/recuperar-datos-disco-duro.jpg",
      descripcion: "Cómo recuperar datos de un disco duro dañado",
      herramientas: [
        "Caja de disco duro externo",
        "Computadora con conexión a internet",
        "Software de recuperación de datos",
      ],
      pasos: [
        "Retira el disco duro dañado de la computadora.",
        "Coloca el disco duro dañado en una caja de disco duro externo.",
        "Conecta la caja de disco duro externo a una computadora funcionando correctamente.",
        "Descarga e instala un software de recuperación de datos confiable.",
        "Abre el software de recuperación de datos y selecciona el disco duro dañado como destino de búsqueda.",
        "Inicia el proceso de escaneo y espera a que el software busque los datos perdidos en el disco duro.",
        "Una vez finalizado el escaneo, revisa los archivos recuperados y selecciona los que deseas recuperar.",
        "Guarda los archivos recuperados en una ubicación segura en otra unidad de almacenamiento.",
        "Si la recuperación no fue exitosa, considera contactar a un servicio profesional de recuperación de datos.",
        "Desconecta la caja de disco duro externo y vuelve a instalar el disco duro en la computadora original (o reemplázalo si es necesario).",
        "Verifica que los archivos recuperados estén en buen estado y que no falte información importante.",
      ],
    },
    // Principal de los productos
  ];
  